- username: GIMP
  acct: GIMP@floss.social
  display_name: GIMP
  avatar: https://todon.eu/system/cache/accounts/avatars/109/155/782/730/207/918/original/fdee5acba261da2a.png
  header: https://todon.eu/system/cache/accounts/headers/109/155/782/730/207/918/original/3bec827897adb118.png
  url: https://floss.social/@GIMP
  note: <p>This is the official Mastodon account of the GNU Image Manipulation
    Program (GIMP). </p><p>GIMP is a cross-platform image editor available for
    GNU/Linux, macOS, Windows and more operating systems. It is free software,
    you can change its source code and distribute your changes.</p><p>Whether
    you are a graphic designer, photographer, illustrator, or scientist, GIMP
    provides you with sophisticated tools to get your job done.</p>
  domain: floss.social
- username: fdroidorg
  acct: fdroidorg@floss.social
  display_name: F-Droid
  avatar: https://todon.eu/system/cache/accounts/avatars/109/177/230/268/787/801/original/2b3bc169afc61b9e.png
  header: https://todon.eu/system/cache/accounts/headers/109/177/230/268/787/801/original/74fe9ee632c0fc7d.jpg
  url: https://floss.social/@fdroidorg
  note: <p>F-Droid is an installable catalogue of FOSS (Free and Open Source
    Software) applications for the Android platform.</p>
  domain: floss.social
- username: thunderbird
  acct: thunderbird@mastodon.online
  display_name: Thunderbird
  avatar: https://todon.eu/system/cache/accounts/avatars/108/196/538/735/743/736/original/411b1c66d35c79bc.png
  header: https://todon.eu/system/cache/accounts/headers/108/196/538/735/743/736/original/d01992adbec16b6c.png
  url: https://mastodon.online/@thunderbird
  note: '<p>Your all-in-one communications command center! Manage multiple email
    accounts, calendars, tasks, RSS feeds and newsgroups. </p><p><a
    href="https://mastodon.online/tags/OpenSource" class="mention hashtag"
    rel="nofollow noopener noreferrer"
    target="_blank">#<span>OpenSource</span></a> and respectful of YOU!
    </p><p>Read about Thunderbird 102 here: <a href="https://mzla.link/3hjVSMQ"
    rel="nofollow noopener noreferrer" target="_blank"><span
    class="invisible">https://</span><span
    class="">mzla.link/3hjVSMQ</span><span
    class="invisible"></span></a></p><p>Get involved with Thunderbird here: <a
    href="https://mzla.link/3Ur3BXu" rel="nofollow noopener noreferrer"
    target="_blank"><span class="invisible">https://</span><span
    class="">mzla.link/3Ur3BXu</span><span
    class="invisible"></span></a></p><p>Get help with Thunderbird here: <a
    href="https://mzla.link/thunderbirdhelp" rel="nofollow noopener noreferrer"
    target="_blank"><span class="invisible">https://</span><span
    class="">mzla.link/thunderbirdhelp</span><span
    class="invisible"></span></a></p>'
  domain: mastodon.online
- username: inkscape
  acct: inkscape@mastodon.art
  display_name: Inkscape
  avatar: https://todon.eu/system/cache/accounts/avatars/000/004/564/original/2920d775e28f94f8.png
  header: https://todon.eu/system/cache/accounts/headers/000/004/564/original/678a807812295363.png
  url: https://mastodon.art/@inkscape
  note: <p>A vector drawing app for Windows, MacOS &amp; GNU/Linux. Free and open
    source, available to everyone! Profile header CC BY-SA 4.0 Chris
    Hildenbrand</p>
  domain: mastodon.art
- username: Krita
  acct: Krita@mastodon.art
  display_name: Krita
  avatar: https://todon.eu/system/cache/accounts/avatars/000/008/666/original/15919500bcd95bc1.jpg
  header: https://todon.eu/system/cache/accounts/headers/000/008/666/original/ebd6f64d8c08c34f.png
  url: https://mastodon.art/@Krita
  note: <p>Free and open source painting software. Get it at krita.org  (Linux,
    Windows, OSX or Android) and talk with other users and devs in the <a
    href="https://mastodon.art/tags/krita" class="mention hashtag" rel="nofollow
    noopener noreferrer" target="_blank">#<span>krita</span></a> channel on
    libera.chat!</p>
  domain: mastodon.art
- username: Blender
  acct: Blender@mastodon.social
  display_name: Blender
  avatar: https://todon.eu/system/cache/accounts/avatars/000/013/836/original/212a778e21b94a9a.jpg
  header: https://todon.eu/system/cache/accounts/headers/000/013/836/original/a536b8dfa3513220.jpg
  url: https://mastodon.social/@Blender
  note: <p>Official account for the Free and Open Source 3D creation suite. Free
    to use for any purpose, forever.</p>
  domain: mastodon.social
- username: kde
  acct: kde@floss.social
  display_name: KDE
  avatar: https://todon.eu/system/cache/accounts/avatars/109/134/920/695/130/789/original/9d23ed47dc55ae2d.png
  header: https://todon.eu/system/cache/accounts/headers/109/134/920/695/130/789/original/c88b74e03046328a.png
  url: https://floss.social/@kde
  note: <p>A worldwide technology community 🌍 Creators of the Plasma desktop
    &amp; a variety of Free and open source applications that let you control
    your digital life.</p>
  domain: floss.social
- username: kdenlive
  acct: kdenlive@floss.social
  display_name: Kdenlive
  avatar: https://todon.eu/system/cache/accounts/avatars/109/137/203/247/990/301/original/f6341e0c06c43653.png
  header: https://todon.eu/system/cache/accounts/headers/109/137/203/247/990/301/original/6409c98be824f37c.jpg
  url: https://floss.social/@kdenlive
  note: <p>Free and Open Source video editing program made by the KDE community.</p>
  domain: floss.social
- username: gnome
  acct: gnome@floss.social
  display_name: GNOME
  avatar: https://todon.eu/system/cache/accounts/avatars/000/004/087/original/5e0ee74a07103a75.jpg
  header: https://todon.eu/system/cache/accounts/headers/000/004/087/original/51c3f0e557fd2d64.jpg
  url: https://floss.social/@gnome
  note: <p>GNOME is a free and open-source software environment project supported
    by a non-profit foundation. Together, the community of contributors and the
    Foundation create a computing platform and software ecosystem, composed
    entirely of free software, that is designed to be elegant, efficient, and
    easy to use.</p>
  domain: floss.social
- username: gnome
  acct: gnome@floss.social
  display_name: GNOME
  avatar: https://todon.eu/system/cache/accounts/avatars/000/004/087/original/5e0ee74a07103a75.jpg
  header: https://todon.eu/system/cache/accounts/headers/000/004/087/original/51c3f0e557fd2d64.jpg
  url: https://floss.social/@gnome
  note: <p>GNOME is a free and open-source software environment project supported
    by a non-profit foundation. Together, the community of contributors and the
    Foundation create a computing platform and software ecosystem, composed
    entirely of free software, that is designed to be elegant, efficient, and
    easy to use.</p>
  domain: floss.social
- username: videolan
  acct: videolan@floss.social
  display_name: VideoLAN
  avatar: https://todon.eu/system/cache/accounts/avatars/109/284/896/663/331/143/original/e059d37205748a88.jpg
  header: https://todon.eu/system/cache/accounts/headers/109/284/896/663/331/143/original/e66efec502bfa686.jpg
  url: https://floss.social/@videolan
  note: <p>Official account of the <a href="https://floss.social/tags/VideoLAN"
    class="mention hashtag" rel="nofollow noopener noreferrer"
    target="_blank">#<span>VideoLAN</span></a> project, <a
    href="https://floss.social/tags/VLC" class="mention hashtag" rel="nofollow
    noopener noreferrer" target="_blank">#<span>VLC</span></a> and the
    community. Open Source Multimedia ftw.</p>
  domain: floss.social
- username: godotengine
  acct: godotengine@mastodon.gamedev.place
  display_name: Godot Engine
  avatar: https://todon.eu/system/cache/accounts/avatars/000/016/481/original/0870696ab4c8042b.png
  header: https://todon.eu/system/cache/accounts/headers/000/016/481/original/d982253acb621886.jpg
  url: https://mastodon.gamedev.place/@godotengine
  note: <p>Advanced, feature-packed, multi-platform 2D and 3D open source game
    engine. It is developed by hundreds of contributors from all around the
    world!</p>
  domain: mastodon.gamedev.place
